# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testcafe_tests:
    name: Run All Tests
    # Save environment variables from Github secrets
    env:
        USER_NAME: ${{ secrets.GIPHY_USER_NAME }}
        PASSWORD: ${{ secrets.GIPHY_PASSWORD }}
        API_KEY: ${{ secrets.GIPHY_API_KEY }}
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository

        uses: actions/checkout@v1
      # Run testcafe tests with report
      - name: Run tests

        uses: DevExpress/testcafe-action@latest

        with:
            args: "chrome Tests/ --reporter html:Reports/testcafeReport.html"

      - name: Install k6 by homebrew

        run: brew install k6
      # Run k6 test with report
      - name: Local k6 test

        run: k6 run ./PerformanceTests.js

      - name: Copy test report
      # Make a directory to deploy to github pages and copy reports together
        run: |
          mkdir public
          cat Reports/testcafeReport.html >> Reports/index.html
          cp -r Reports/index.html public/
      # Deploy test report to github pages
      - name: Deploy

        uses: peaceiris/actions-gh-pages@v3

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
